# Generated by Django 2.2.6 on 2019-10-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20191029_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='설명'),
        ),
    ]
