# Generated by Django 2.2.6 on 2019-10-28 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100, verbose_name='상호')),
                ('business_registration_number', models.CharField(max_length=10, verbose_name='등록번호')),
                ('representative_name', models.CharField(max_length=30, verbose_name='대표자명')),
                ('business_address', models.CharField(max_length=100, verbose_name='업장소재지')),
                ('registration_image', models.ImageField(upload_to='partners/certificates', verbose_name='사업자 등록증')),
                ('business_commencement_date', models.DateField(null=True, verbose_name='영업개시일')),
                ('business_type', models.CharField(max_length=30, null=True, verbose_name='업태')),
                ('business_item', models.CharField(max_length=30, null=True, verbose_name='종목')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Partner', verbose_name='파트너')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.Store', verbose_name='가게')),
            ],
            options={
                'verbose_name': '사업자등록증',
                'verbose_name_plural': '사업자등록증',
                'ordering': ['id'],
            },
        ),
    ]
