# Generated by Django 2.2.6 on 2019-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
