# Generated by Django 2.2.6 on 2019-10-18 04:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('lon', models.FloatField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('lat', models.FloatField(validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)])),
                ('thumbnail', models.TextField(blank=True, default='')),
                ('contact', models.CharField(blank=True, default='', max_length=15)),
                ('road_addr', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=50)),
                ('tags', models.TextField(blank=True, default='')),
                ('price_average', models.IntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('booking', models.BooleanField(default=False)),
                ('group_seat', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('togo', models.BooleanField(default=False)),
                ('review_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.Category')),
                ('partner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Partner')),
            ],
        ),
    ]
