# Generated by Django 2.2.6 on 2019-10-23 10:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=30, verbose_name='대분류')),
                ('sub_category', models.CharField(max_length=30, verbose_name='중분류')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='옵션명')),
            ],
            options={
                'verbose_name': '옵션',
                'verbose_name_plural': '옵션',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.CharField(max_length=20, unique=True, verbose_name='네이버 아이디')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('thumbnail', models.TextField(blank=True, default='', verbose_name='대표 사진')),
                ('contact', models.CharField(blank=True, default='', max_length=15, verbose_name='전화번호')),
                ('road_addr', models.CharField(max_length=50, verbose_name='도로명 주소')),
                ('common_addr', models.CharField(max_length=50, verbose_name='시구')),
                ('addr', models.CharField(max_length=50, verbose_name='지번 주소')),
                ('tags', models.TextField(blank=True, default='', verbose_name='태그')),
                ('price_avg', models.IntegerField(default=0, verbose_name='가격대')),
                ('review_cnt', models.IntegerField(default=0, verbose_name='네이버 리뷰갯수')),
                ('view_cnt', models.IntegerField(default=0, verbose_name='조회수')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.Category', verbose_name='카테고리')),
                ('options', models.ManyToManyField(blank=True, to='stores.Option', verbose_name='옵션')),
                ('partner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Partner', verbose_name='파트너')),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='상호')),
                ('business_registration_number', models.CharField(max_length=10, verbose_name='등록번호')),
                ('representative_name', models.CharField(max_length=30, verbose_name='대표자명')),
                ('business_address', models.CharField(max_length=100, verbose_name='업장소재지')),
                ('registration_image', models.ImageField(upload_to='partners/certificates', verbose_name='사업자 등록증')),
                ('business_commencement_date', models.DateField(null=True, verbose_name='영업개시일')),
                ('business_type', models.CharField(max_length=30, null=True, verbose_name='업태')),
                ('business_item', models.CharField(max_length=30, null=True, verbose_name='종목')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Partner', verbose_name='파트너')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.Store', verbose_name='가게')),
            ],
            options={
                'verbose_name': '사업자등록증',
                'verbose_name_plural': '사업자등록증',
                'ordering': ['id'],
            },
        ),
    ]
