# Generated by Django 2.2.6 on 2019-10-25 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessRegistration',
        ),
    ]
